services:
  searxng:
    image: searxng/searxng:latest
    ports:
      - "11505:8080"
    volumes:
      - ./linux/searxng:/etc/searxng
    restart: always
  
  open-webui:
    image: ghcr.io/open-webui/open-webui:ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "11500:8080"
    volumes:
      - ./linux/open-webui:/app/backend/data
    environment:
      - WEBUI_AUTH=False
      - WEBUI_SESSION_COOKIE_SAME_SITE=None
      - WEBUI_SESSION_COOKIE_SECURE=True
      - ENABLE_RAG_WEB_SEARCH=True
      - ENABLE_EVALUATION_ARENA_MODELS=False
      - RAG_WEB_SEARCH_ENGINE=searxng
      - DEFAULT_MODELS=tinyllama
      - SEARXNG_QUERY_URL=http://host.docker.internal:11505
      # - ENV=dev
      # - ENABLE_PERSISTENT_CONFIG=True
      - CUSTOM_NAME="y0n1x's AI Lab"
      - WEBUI_NAME=y0n1x's AI Lab
      # - WEBUI_URL=http://localhost:11500
      # - ENABLE_SIGNUP=True
      # - ENABLE_LOGIN_FORM=True
      # - ENABLE_REALTIME_CHAT_SAVE=False
      # - ENABLE_ADMIN_EXPORT=True
      # - ENABLE_ADMIN_CHAT_ACCESS=True
      # - ENABLE_CHANNELS=False
      # - ADMIN_EMAIL=""
      # - SHOW_ADMIN_DETAILS=True
      # - BYPASS_MODEL_ACCESS_CONTROL=False
      # - DEFAULT_USER_ROLE=pending
      # - DEFAULT_LOCALE=fr
      # - WEBHOOK_URL=""
      # - WEBUI_BUILD_HASH=dev-build
      # - AIOHTTP_CLIENT_TOTAL_CONN=100
      # - AIOHTTP_CLIENT_MAX_SIZE_CONN=10
      # - AIOHTTP_CLIENT_READ_TIMEOUT=600
      # - AIOHTTP_CLIENT_CONN_TIMEOUT=60
      # - LOG_LEVEL=INFO
      # - LOG_FORMAT=default
      # - ENABLE_FILE_LOGGING=False
      # - LOG_MAX_BYTES=10485760
      # - LOG_BACKUP_COUNT=5
      # - OLLAMA_BASE_URL=""
      # - OLLAMA_BASE_URLS=""
      # - OLLAMA_API_KEY=""
      # - OLLAMA_KEEP_ALIVE=""
      # - OLLAMA_REQUEST_TIMEOUT=300
      # - OLLAMA_NUM_PARALLEL=1
      # - OLLAMA_MAX_QUEUE=100
      # - ENABLE_OLLAMA_MULTIMODAL_SUPPORT=False
      # - OPENAI_API_BASE_URL=""
      # - OPENAI_API_KEY=""
      # - ENABLE_OPENAI_API_KEY=False
      # - ENABLE_OPENAI_API_BROWSER_EXTENSION_ACCESS=False
      # - OPENAI_API_KEY_GENERATION_ENABLED=False
      # - OPENAI_API_KEY_GENERATION_ROLE=user
      # - OPENAI_API_KEY_EXPIRATION_TIME_IN_MINUTES=0
      # - TASKS_MAX_RETRIES=3
      # - TASKS_RETRY_DELAY=60
      # - ENABLE_AUTOCOMPLETE=False
      # - AUTOCOMPLETE_PROVIDER=ollama
      # - AUTOCOMPLETE_MODEL=""
      # - AUTOCOMPLETE_NO_STREAM=True
      # - AUTOCOMPLETE_INSECURE=True
      # - EVALUATION_ARENA_MODELS_TAGS_ENABLED=False
      # - EVALUATION_ARENA_MODELS_TAGS_GENERATION_MODEL=""
      # - EVALUATION_ARENA_MODELS_TAGS_GENERATION_PROMPT=""
      # - EVALUATION_ARENA_MODELS_TAGS_GENERATION_PROMPT_MIN_LENGTH=100
      # - API_KEYS_ENDPOINT_ACCESS_NONE=True
      # - API_KEYS_ENDPOINT_ACCESS_ALL=False
      # - ENABLE_RAG=True
      # - RAG_EMBEDDING_ENGINE=ollama
      # - RAG_EMBEDDING_MODEL=""
      # - RAG_EMBEDDING_MODEL_AUTOUPDATE=True
      # - RAG_EMBEDDING_MODEL_TRUST_REMOTE_CODE=False
      # - RAG_EMBEDDING_OPENAI_API_BASE_URL=""
      # - RAG_EMBEDDING_OPENAI_API_KEY=""
      # - RAG_RERANKING_MODEL=""
      # - RAG_RERANKING_MODEL_AUTOUPDATE=True
      # - RAG_RERANKING_MODEL_TRUST_REMOTE_CODE=False
      # - RAG_RERANKING_TOP_K=3
      # - RAG_REQUEST_TIMEOUT=300
      # - RAG_CHUNK_SIZE=1500
      # - RAG_CHUNK_OVERLAP=100
      # - RAG_NUM_SOURCES=4
      # - RAG_OPENAI_API_KEY=""
      # - RAG_PDF_EXTRACTION_LIBRARY=pypdf
      # - RAG_COPY_UPLOADED_FILES_TO_VOLUME=False
      # - RAG_WEB_SEARCH_LLM_TIMEOUT=120
      # - RAG_WEB_SEARCH_RESULT_COUNT=3
      # - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10
      # - RAG_WEB_SEARCH_BACKEND_TIMEOUT=120
      # - RAG_BRAVE_SEARCH_API_KEY=""
      # - RAG_GOOGLE_SEARCH_API_KEY=""
      # - RAG_GOOGLE_SEARCH_ENGINE_ID=""
      # - RAG_SERPER_API_KEY=""
      # - RAG_SERPAPI_API_KEY=""
      # - RAG_DUCKDUCKGO_SEARCH_ENABLED=True
      # - RAG_SEARCHAPI_API_KEY=""
      # - RAG_WEB_LOADER_URL_BLACKLIST=""
      # - RAG_WEB_LOADER_CONTINUE_ON_FAILURE=False
      # - RAG_WEB_LOADER_MODE=html2text
      # - RAG_WEB_LOADER_SSL_VERIFICATION=True
      # - RAG_YOUTUBE_LOADER_LANGUAGE=en
      # - RAG_YOUTUBE_LOADER_TRANSLATION=fr
      # - RAG_YOUTUBE_LOADER_ADD_VIDEO_INFO=False
      # - RAG_YOUTUBE_LOADER_CONTINUE_ON_FAILURE=False
      # - WHISPER_MODEL=small-fr
      # - WHISPER_MODEL_AUTOUPDATE=True
      # - WHISPER_MODEL_TRUST_REMOTE_CODE=False
      # - WHISPER_DEVICE=cpu
      # - STT_ENGINE=""
      # - STT_OPENAI_API_BASE_URL=""
      # - STT_OPENAI_API_KEY=""
      # - TTS_ENGINE=""
      # - AZURE_TTS_KEY=""
      # - AZURE_TTS_REGION=""
      # - OPENAI_TTS_API_BASE_URL=""
      # - OPENAI_TTS_API_KEY=""
      # - IMAGE_GENERATION_ENGINE=""
      # - AUTOMATIC1111_BASE_URL=""
      # - COMFYUI_BASE_URL=""
      # - OPENAI_DALLE_API_BASE_URL=""
      # - OPENAI_DALLE_API_KEY=""
      # - ENABLE_OAUTH_LOGIN=False
      # - ENABLE_OAUTH_SIGNUP=False
      # - OAUTH_METADATA_URL=""
      # - OAUTH_CLIENT_ID=""
      # - OAUTH_CLIENT_SECRET=""
      # - OAUTH_REDIRECT_URI=""
      # - OAUTH_AUTHORIZATION_ENDPOINT=""
      # - OAUTH_TOKEN_ENDPOINT=""
      # - OAUTH_USERINFO_ENDPOINT=""
      # - OAUTH_JWKS_URI=""
      # - OAUTH_CALLBACK_PATH=/oauth/callback
      # - OAUTH_LOGIN_CALLBACK_URL=""
      # - OAUTH_AUTO_CREATE_ACCOUNT=False
      # - OAUTH_AUTO_UPDATE_ACCOUNT_INFO=False
      # - OAUTH_LOGOUT_REDIRECT_URL=""
      # - OAUTH_SCOPES=openid email profile
      # - OAUTH_DISPLAY_NAME=OpenID
      # - OAUTH_LOGIN_BUTTON_TEXT=Sign in with OpenID
      # - OAUTH_TIMEOUT=10
      # - LDAP_ENABLED=False
      # - LDAP_URL=""
      # - LDAP_PORT=389
      # - LDAP_TLS=False
      # - LDAP_TLS_CERT_PATH=""
      # - LDAP_TLS_KEY_PATH=""
      # - LDAP_TLS_CA_CERT_PATH=""
      # - LDAP_TLS_REQUIRE_CERT=CERT_NONE
      # - LDAP_BIND_DN=""
      # - LDAP_BIND_PASSWORD=""
      # - LDAP_BASE_DN=""
      # - LDAP_USERNAME_ATTRIBUTE=uid
      # - LDAP_GROUP_MEMBERSHIP_FILTER=""
      # - LDAP_ADMIN_GROUP=""
      # - LDAP_USER_GROUP=""
      # - LDAP_LOGIN_FALLBACK=False
      # - LDAP_AUTO_CREATE_ACCOUNT=False
      # - LDAP_AUTO_UPDATE_ACCOUNT_INFO=False
      # - LDAP_TIMEOUT=10
      # - ENABLE_WORKSPACE_PERMISSIONS=False
      # - ENABLE_CHAT_PERMISSIONS=False
      # - DATABASE_POOL_SIZE=0
      # - DATABASE_POOL_MAX_OVERFLOW=0
      # - DATABASE_POOL_TIMEOUT=30
      # - DATABASE_POOL_RECYCLE=3600
      # - REDIS_URL=""
      # - REDIS_SENTINEL_HOSTS=""
      # - REDIS_SENTINEL_PORT=26379
      # - ENABLE_WEBSOCKET_SUPPORT=False
      # - WEBSOCKET_MANAGER=redis
      # - WEBSOCKET_REDIS_URL=""
      # - WEBSOCKET_SENTINEL_HOSTS=""
      # - WEBSOCKET_SENTINEL_PORT=26379
      # - UVICORN_WORKERS=1
      # - http_proxy=""
      # - https_proxy=""
      # - no_proxy=""
      # - PIP_OPTIONS=""
      # - PIP_PACKAGE_INDEX_OPTIONS=""
    restart: always

  docling-serve:
    image: quay.io/docling-project/docling-serve
    ports:
      - "11501:5001"
    environment:
      - DOCLING_SERVE_ENABLE_UI=true
    restart: always

  openai-edge-tts:
    image: travisvn/openai-edge-tts:latest
    ports:
      - "11502:5050"
    restart: always

  jupyter:
    image: jupyter/minimal-notebook:latest
    container_name: jupyter-notebook
    ports:
      - "11504:8888"
    volumes:
      - ./linux/jupyter:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=123456
    restart: always

# volumes:
#   open-webui:
