name: Build
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - id: tags
      name: Calculate tags
      shell: bash
      run: |
        prefix=ghcr.io/${{ github.repository }}
        echo "TAGS<<##" >> "$GITHUB_OUTPUT"
        ref=${{ github.ref }}
        case "$ref" in
          refs/heads/main)
            echo "$prefix:latest" >> "$GITHUB_OUTPUT";;
          refs/tags/v[0-9]*)
            echo "$prefix:${ref#refs/tags/}" >> "$GITHUB_OUTPUT";;
          *)
            echo "$prefix:${{ github.sha }}" >> "$GITHUB_OUTPUT";;
        esac
        echo "##" >> "$GITHUB_OUTPUT"
    - id: searxng_tags
      name: Calculate searxng tags
      shell: bash
      run: |
        prefix=ghcr.io/${{ github.repository }}
        echo "TAGS<<##" >> "$GITHUB_OUTPUT"
        ref=${{ github.ref }}
        # Always push :searxng tag
        echo "$prefix:searxng" >> "$GITHUB_OUTPUT"
        case "$ref" in
          refs/heads/main)
            echo "$prefix:latest-searxng" >> "$GITHUB_OUTPUT";;
          refs/tags/v[0-9]*)
            echo "$prefix:${ref#refs/tags/}-searxng" >> "$GITHUB_OUTPUT";;
          *)
            echo "$prefix:${{ github.sha }}-searxng" >> "$GITHUB_OUTPUT";;
        esac
        echo "##" >> "$GITHUB_OUTPUT"
    - uses: docker/setup-qemu-action@v3
      with:
        platforms: amd64,arm64
    - uses: docker/setup-buildx-action@v3
      with:
        platforms: |
          linux/amd64
          linux/arm64
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v6
      with:
        platforms: |
          linux/amd64
          linux/arm64
        push: ${{ github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main') }}
        tags: ${{ steps.tags.outputs.TAGS }}
    - uses: docker/build-push-action@v6
      name: Build and push searxng image
      with:
        context: .
        file: ./Dockerfile.searxng
        platforms: |
          linux/amd64
          linux/arm64
        push: ${{ github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main') }}
        tags: ${{ steps.searxng_tags.outputs.TAGS }}
